### ISSUE TITLE
Incorrect Working Directory for Interactive Desktop Job on Node

### ISSUE THREAD

**Issue by ColonelPanicks** [openflighthpc/flight-job#93]
When I try to create an interactive desktop job on a node I'm seeing an odd inconsistency.

I have the following within the `create_session_script <<SESSION` section of the template:
```
<snip>
echo "Executing job commands, current working directory is $(pwd)" >> "${SESSION_OUTPUT}" 2>&1

# REPLACE THE FOLLOWING WITH YOUR APPLICATION COMMANDS
ls
cat ipython.ipynb
jupyter notebook ipython.ipynb

echo "This is an example interactive job running a bash shell." >> "${SESSION_OUTPUT}" 2>&1
<snip>
```

My session.output shows the correct pwd
```
Executing job commands, current working directory is /home/flight/jupyter-demo
This is an example interactive job running a bash shell.
```

However the terminal the pwd is `~`. 
<img width="477" alt="Screenshot 2022-04-22 at 18 30 19" src="https://user-images.githubusercontent.com/27725639/164764962-042e8dc4-a768-4412-ab10-efd16e26d2b1.png">

I think this confusion in output is coming because the heredoc for the creation of the session script is going to be evaluating all `$` items which means `$(pwd)` is being evaluated within the job script but is in no way passed session script for launching things within the desktop. 

I've been able to fix this by adding `cd $(pwd)` into the `create_session_script << SESSION` section right before the `REPLACE THE FOLLOWING WITH YOUR APPLICATION COMMANDS` message. Would this be the best approach for fixing it in the packaged template?

**Comment by benarmston** [comment]
Good spot @ColonelPanicks.
